min_time = 8
max_time = 10
minbetodd = 1.9
maxbetodd = 5
insufficient = 20
threshold = 1
n_iter = 10 # BayesSearch
cv = 5 # BayesSearch
epochs = 200 # for neuralnetwork
patience = 40 # for neuralnetwork