min_time = 19
max_time = 21
minbetodd = 1.9
maxbetodd = 2.9
insufficient = 20
threshold = 1
n_iter = 2 # BayesSearch
cv = 2 # BayesSearch
epochs = 100 # for neuralnetwork
patience = 20 # for neuralnetwork